[package]
authors = ["Augustus Mayo <gusmayo@gmail.com>"]
name = "banner"
version = "0.1.0"

[dependencies]
iron = "0.6.0"
log = "0.4.1"
mount = "0.4.0"
router = "0.6.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

[dependencies.redis]
optional = true
version = "0.8.0"

[features]
redis-backend = ["redis"]
