version: 2.0
jobs:
  mem-test:
    docker:
      - image: clux/muslrust
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test --features mem-backend
  mongo-test:
    docker:
      - image: clux/muslrust
      - image: circleci/mongo
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test --features mongo-backend
  redis-test:
    docker:
      - image: clux/muslrust
      - image: redis
    steps:
      - checkout
      - run:
          name: install dockerize
          command: apt-get update && apt-get install -y wget && wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Test
          command: cargo test --features redis-backend

workflows:
  version: 2
  test:
    jobs:
      - mem-test
      - mongo-test
      - redis-test